// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEoqTiL_BIXouF4o_tBvDM9lz2OuozDDY',
    appId: '1:486155576858:web:f228da79044cc3051c13a3',
    messagingSenderId: '486155576858',
    projectId: 'taskrbuy',
    authDomain: 'taskrbuy.firebaseapp.com',
    storageBucket: 'taskrbuy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCneo2ZbGoqEmblTaFSk4DzWalWChTrgwM',
    appId: '1:486155576858:android:022e99460c60590e1c13a3',
    messagingSenderId: '486155576858',
    projectId: 'taskrbuy',
    storageBucket: 'taskrbuy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJb3BW--pgZtXcOQZMUgfQi6J1r2e7jYM',
    appId: '1:486155576858:ios:375d096bb6c2cf261c13a3',
    messagingSenderId: '486155576858',
    projectId: 'taskrbuy',
    storageBucket: 'taskrbuy.appspot.com',
    androidClientId: '486155576858-i5phofd3n71bc62qg6vgf5m0eruo19k5.apps.googleusercontent.com',
    iosClientId: '486155576858-n42gooftb1oee47lmoq1ebq59j03ejj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskrbuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJb3BW--pgZtXcOQZMUgfQi6J1r2e7jYM',
    appId: '1:486155576858:ios:375d096bb6c2cf261c13a3',
    messagingSenderId: '486155576858',
    projectId: 'taskrbuy',
    storageBucket: 'taskrbuy.appspot.com',
    androidClientId: '486155576858-i5phofd3n71bc62qg6vgf5m0eruo19k5.apps.googleusercontent.com',
    iosClientId: '486155576858-n42gooftb1oee47lmoq1ebq59j03ejj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskrbuy',
  );
}
